### ISSUE TITLE
Can't add plugin [Error] System.BadImageFormatException: Bad IL format

### ISSUE THREAD

**Issue by Justsomeotakuu** [CEO-Chair/TerraAngel#54]
[Error] System.BadImageFormatException: Bad IL format.
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromStream(Stream assembly, Stream assemblySymbols)
   at TerraAngel.Plugin.PluginLoader.LoadAndInitializePlugins() in C:\Users\User\Desktop\TerraAngel\src\TerraAngel\Terraria\TerraAngel\Plugin\PluginLoader.cs:line 32

**Comment by CEO-Chair** [comment]
Plugins must be compiled .NET 7.0 assemblies. See [plugins documentation](https://github.com/CEO-Chair/TerraAngel/blob/master/PLUGINS.md) for instructions on how to create a plugin.

**Comment by Justsomeotakuu** [comment]
Oh yeah sorry i fixed it thanks, i love your client
