### ISSUE TITLE
Error occurs during fast_start.bat

### ISSUE THREAD

**Issue by ZekusV** [CEO-Chair/TerraAngel#9]
![image](https://user-images.githubusercontent.com/112866998/193451205-9c34a8cf-716e-4a70-9f17-67208ba554f4.png)

++++++++++

![image](https://user-images.githubusercontent.com/112866998/193451233-084d18d3-3456-4f05-b449-70f5b8ac1321.png)

**Comment by CEO-Chair** [comment]
This is because you are using the 1.4.3.6 version of the client. Clone with `--branch dev-1.4.4.2` to use with the latest version of Terraria

**Comment by ZekusV** [comment]
`System.DllNotFoundException: Could not load cimgui
   at TerraAngel.ClientLoader.<>c.<LoadClientInteral>b__32_0(String libraryName, Assembly assembly, Nullable`1 searchPath) in C:\Users\zekeb\TerraAngel\src\TerraAngel\Terraria\TerraAngel\ClientLoader.cs:line 87
   at System.Runtime.InteropServices.NativeLibrary.LoadLibraryCallbackStub(String libraryName, Assembly assembly, Boolean hasDllImportSearchPathFlags, UInt32 dllImportSearchPathFlags)
   at ImGuiNET.ImGuiNative.igGetCurrentContext()
   at TerraAngel.Client.Config.ClientUIConfig.get_StyleColors() in C:\Users\zekeb\TerraAngel\src\TerraAngel\Terraria\TerraAngel\Client\Config\ClientUIConfig.cs:line 22
   at TerraAngel.Client.Config.ClientUIConfig.Get() in C:\Users\zekeb\TerraAngel\src\TerraAngel\Terraria\TerraAngel\Client\Config\ClientUIConfig.cs:line 154
   at TerraAngel.Client.Config.ClientConfig.WriteToFile() in C:\Users\zekeb\TerraAngel\src\TerraAngel\Terraria\TerraAngel\Client\Config\ClientConfig.cs:line 297
   at TerraAngel.Client.Config.ClientConfig.ReadFromFile() in C:\Users\zekeb\TerraAngel\src\TerraAngel\Terraria\TerraAngel\Client\Config\ClientConfig.cs:line 319
   at TerraAngel.ClientLoader.LoadClientInteral() in C:\Users\zekeb\TerraAngel\src\TerraAngel\Terraria\TerraAngel\ClientLoader.cs:line 126
   at TerraAngel.ClientLoader.LoadClient() in C:\Users\zekeb\TerraAngel\src\TerraAngel\Terraria\TerraAngel\ClientLoader.cs:line 163`
